### ISSUE TITLE
Troubleshoot server logon issues

### ISSUE THREAD

**Issue by patudom** [cosmicds/noncode-issues#22]
Things to try:

- [x] Jon - Cache hashing of keys on cosmicds server.

Things to do:

- [x] Jon - check in with Nick if there are tasks that can be shared - WWT in Solara
- [x] Pat - create accounts for SED Swap trial.

**Comment by Carifio24** [comment]
See https://github.com/cosmicds/cds-api/pull/99 for the first item in the list.
